import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Color backgroundColor = const Color(0xFFE5E5E5);
Color loginBackgroundColor = const Color(0xFFF3F5F6);
Color liveTextColor = const Color(0xFF767DFF);
Color mediumTextColor = const Color(0xFF9395A4);
Color buttonBlue = const Color(0xFF118AB2);
Color accent = const Color(0xFF1FFFED);
Color primary = const Color(0xFF118AB2);
Color titleColor = const Color(0xFF191C32);
Color subTitleColor = const Color(0xFF26273C);
Color highlight = const Color(0xFF284047);
Color white = const Color(0xFFFFFFFF);
Color headerTextColor = const Color(0xFF2713A3);
Color mildHeaderTextColor = const Color(0x802713A3);
Color appYellow = const Color(0xFFF0B84D);
Color tableTextOrange = const Color(0xFFF2994A);
Color tableTextGreen = const Color(0xFF67B519);
Color tableGreen = const Color(0xFFEEFBCF);
Color tableOrange = const Color(0xFFFEF3DB);
